hpc <- read.csv("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=F)
hpc2 <- subset(hpc, hpc$Date %in% c("1/2/2007", "2/2/2007"))
hpc3 <- subset(hpc2, hpc2$Global_active_power != "?")
x <- paste(as.Date(hpc3$Date,"%d/%m/%Y"), hpc3$Time)
hpc3$DtTm <- strptime(x, "%Y-%m-%d %H:%M:%S")
png("plot2.png", width = 480, height = 480)
plot(hpc3$DtTm, hpc3$Global_active_power, type="n", ylab="Global Active Power (kilowatts)", xlab="")
lines(hpc3$DtTm, hpc3$Global_active_power)
dev.off()
